### ISSUE TITLE
number of tracks not equal by pypianoroll and pretty_midi

### ISSUE THREAD

**Issue by ruiguo-bio** [salu133445/pypianoroll#4]
Hello Hao-wen.  I find the number of tracks are different by pypianoroll and pretty-midi on a number of files. I assume they should have the same track number because pypinaoroll is based on pretty-midi data. I attach one file with that issue for your reference. Thanks.

[test.mid.zip](https://github.com/salu133445/pypianoroll/files/3064660/test.mid.zip)

**Comment by salu133445** [comment]
Hi, they do have the same number of tracks in my case. Here is the code I ran.

```python
# pypianoroll
>>> from pypianoroll import Multitrack
>>> m = Multitrack("./test.mid")
>>> len(m.tracks)
12

# pretty_midi
>>> from pretty_midi import PrettyMIDI
>>> pm = PrettyMIDI("./test.mid")
>>> len(pm.instruments)
12
```

**Comment by ruiguo-bio** [comment]
Sorry, I think the file attached below shows the issue. pretty-midi shows 14 tracks, and pypianoroll shows 12 tracks. The same happens on a number of files.
[iheardursongs.mid.zip](https://github.com/salu133445/pypianoroll/files/3072666/iheardursongs.mid.zip)

**Comment by salu133445** [comment]
The missing two tracks are the last two tracks, whose notes are way shorter than one unit in the default temporal resolution. Here is the code snippet I ran.
```python
>>> import numpy as np
>>> from pretty_midi import PrettyMIDI
>>> pm = PrettyMIDI("./iheardursongs.mid")

# The first track
>>> np.mean([(n.end - n.start) for n in pm.instruments[0].notes])
0.3432162994224421
>>> min([(n.end - n.start) for n in pm.instruments[0].notes])
0.13297854166665957

# The second last track
>>> max([n.end - n.start for n in pm.instruments[-2].notes])
0.00531914166668912

# The last track
>>> max([(n.end - n.start) for n in pm.instruments[-1].notes])
0.005434774999997671
```
The notes in the last two tracks are too short so that they are removed when we quantize the temporal axis. Hence, they will be converted into two empty pianorolls. Since the `skip_empty_tracks` option in the `Multitrack.parse_pretty_midi()` method is set to True by default, the two tracks are removed.
