### ISSUE TITLE
pypianoroll.parse() is skipping the first notes

### ISSUE THREAD

**Issue by GuiMarion** [salu133445/pypianoroll#6]
Hi all and thank you for this very handy module! 

I am facing an issue, I have some midi files which, once imported with pypianoroll, have the first notes skipped. 

Please use the attached midi file to reproduce the error. 
Code to reproduce the error:

import pypianoroll 
import matplotlib.pyplot as plt
k = pypianoroll.parse("chor-038.mid")
k.plot()
plt.show()

 By the way it happened with a number of files.

Thank you by advance!! 
[chor-038.mid.zip](https://github.com/salu133445/pypianoroll/files/3384242/chor-038.mid.zip)

**Comment by salu133445** [comment]
Hi, this is probably caused by a bad `first_beat_time` estimation. Since in pypianoroll the temporal axis of the parsed pianoroll is supposed to be beat-quantized, we need to first estimate the timing of the first beat. By default, `pretty_midi.PrettyMIDI.estimate_beat_start()` is called. However, this can be error-prone and the accuracy depends largely on types of the input MIDI files.

If you know the exact timing of the first beat, you can instead pass it to the parse function by using the algorithm 'custom', e.g.,`pypianoroll.Multitrack.parse_pretty_midi(algorithm='custom', first_beat_time=0.0)`. Note that the `pypianoroll.parse()` does not support these options yet. A pull request is welcome.

There is also another algorithm 'strict', which acquire the first beat information by time signature change event. This is more robust than estimating the beat start time. However, there are some potential problems of this algorithm.
- there can be no time signature events at all -> an error will be raised then
- the first time signature change event can happen in the middle of the song -> notes before the first time signature change event will be discarded
- the first time signature is wrong as it was inserted by the editing software by default

There is no easy way to bypass this issue as beat information is usually missing or erroneous in MIDI files. Do let me know if you figure out any better ways to do so.

**Comment by GuiMarion** [comment]
Thank you very much for this information! I just used custom algo with first_beat_time=0.0. It added some silence at the beginning but it's easy to remove. I will see if I can add this functionality to your repo.

Thanks!

**Comment by salu133445** [comment]
Cool. That would be nice.
